export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOK = 'GET_BOOK';
export const SET_CURRENT_BOOK_LOADING = 'SET_CURRENT_BOOK_LOADING';
export const SET_BOOKS_LOADING = 'SET_BOOKS_LOADING'; 
export const REGISTER_USER = 'REGISTER_USER';
export const LOAD_USER = 'LOAD_USER';
export const SET_USER_PROFILE_LOADING = 'SET_USER_PROFILE_LOADING';