export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOK = 'GET_BOOK';
export const SET_CURRENT_BOOK_LOADING = 'SET_CURRENT_BOOK_LOADING';
export const SET_BOOKS_LOADING = 'SET_BOOKS_LOADING'; 
export const CLEAR_BOOK = 'CLEAR_BOOK';
export const ADD_FINISHED_BOOK = 'ADD_FINISHED_BOOK';
export const LOAD_BOOK_PERSONAL_INFO = 'LOAD_BOOK_PERSONAL_INFO';

export const REGISTER_USER = 'REGISTER_USER';
export const LOAD_USER = 'LOAD_USER';
export const SET_USER_PROFILE_LOADING = 'SET_USER_PROFILE_LOADING';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SUCCESS_LOAD_USER = 'SUCCESS_LOAD_USER';
export const FAIL_AUTH = 'FAIL_AUTH';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
